CREATE TABLE IF NOT EXISTS holdings (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  symbol VARCHAR(10) NOT NULL,
  quantity DOUBLE NOT NULL,
  average_price DOUBLE NOT NULL,
  value DOUBLE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
); 