CREATE TABLE IF NOT EXISTS positions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  symbol VARCHAR(10) NOT NULL,
  quantity DOUBLE NOT NULL,
  entry_price DOUBLE NOT NULL,
  current_price DOUBLE NOT NULL,
  pnl DOUBLE NOT NULL,
  pnl_pct DOUBLE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
); 