CREATE TABLE IF NOT EXISTS orderbook (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  symbol VARCHAR(10) NOT NULL,
  quantity DOUBLE NOT NULL,
  side ENUM('BUY','SELL') NOT NULL,
  price DOUBLE NOT NULL,
  unrealized_pnl DOUBLE NOT NULL,
  realized_pnl DOUBLE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
); 